language: java
jdk: oraclejdk6
env:
    matrix:
    #- ANDROID_TARGET=android-8   ANDROID_SDKS=android-8,build-tools-17.0.0            ANDROID_BUILD_TOOLS_VERSION=17.0.0 ANDROID_ABI=armeabi
    #- ANDROID_TARGET=android-10  ANDROID_SDKS=android-10,build-tools-17.0.0,sysimg-10 ANDROID_BUILD_TOOLS_VERSION=17.0.0 ANDROID_ABI=armeabi
    #- ANDROID_TARGET=android-15  ANDROID_SDKS=android-15,build-tools-17.0.0,sysimg-15 ANDROID_BUILD_TOOLS_VERSION=17.0.0 ANDROID_ABI=armeabi-v7a
    #- ANDROID_TARGET=android-17  ANDROID_SDKS=android-17,build-tools-17.0.0,sysimg-17 ANDROID_BUILD_TOOLS_VERSION=17.0.0 ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-18  ANDROID_SDKS=android-18,build-tools-18.0.1,sysimg-18 ANDROID_BUILD_TOOLS_VERSION=18.0.1 ANDROID_ABI=armeabi-v7a

before_install:
    # Install base Android SDK
    - sudo apt-get update -qq
    - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch; fi
    - wget http://dl.google.com/android/android-sdk_r22.0.5-linux.tgz
    - tar xzf android-sdk_r22.0.5-linux.tgz
    - export ANDROID_HOME=`pwd`/android-sdk-linux
    - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${ANDROID_HOME}/build-tools/$ANDROID_BUILD_TOOLS_VERSION

    # Install required Android components.
    - android list sdk --extended
    # Do you accept the license 'android-sdk-license-bcbbd656' [y/n]:
    - echo -e "y\n" > accept.txt
    - android update sdk --filter platform-tools,extra-android-support,$ANDROID_SDKS --no-ui --force < accept.txt

    # PROVISIONAL: changed SDKr22 build-tools path. create symbolic link
    - if [ ! -e ${ANDROID_HOME}/platform-tools/aapt ]; then ln -s ${ANDROID_HOME}/build-tools/$ANDROID_BUILD_TOOLS_VERSION/aapt ${ANDROID_HOME}/platform-tools/aapt; fi
    - if [ ! -e ${ANDROID_HOME}/platform-tools/aidl ]; then ln -s ${ANDROID_HOME}/build-tools/$ANDROID_BUILD_TOOLS_VERSION/aidl ${ANDROID_HOME}/platform-tools/aidl; fi

    # Create and start emulator
    - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
    - emulator -avd test -no-skin -no-audio -no-window &

    ## PROVISIONAL: android-maven-plugin 3.6.0
    #- git clone git://github.com/jayway/maven-android-plugin.git android-maven-plugin
    #- cd android-maven-plugin
    #- git checkout -b refs/tags/3.6.0
    #- mvn clean install
    #- cd ..

before_script:
    # Make sure the emulator has started before running tests
    - chmod +x ./wait_for_emulator
    - ./wait_for_emulator

script: mvn install -Pintegration-tests -Dandroid.device=test
